### ISSUE TITLE
where is the code？

### ISSUE THREAD

**Issue by Fateeeeee** [henrylee2570/NoisyAnchor#2]
Thank you for your work. I have not used detectron, could you please tell me the file location of this Noisy Anchor implementation?

**Comment by henrylee2570** [comment]
Thanks for your interest in our work! 

The implementation of our method is mainly in `./detectron2/modeling/meta_arch/retinanet_noisy.py` and `./detectron2/modeling/matcher.py`. The configs are under `./configs/COCO-Detection-NoisyAnchor`.

**Comment by Fateeeeee** [comment]
Thanks ！ I found it
